# Generated by Django 5.0.6 on 2024-07-03 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompressedImage",
            new_name="ImageUpload",
        ),
    ]
