# Generated by Django 5.0.6 on 2024-07-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_compressedimage_imageupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="original_images/"
                    ),
                ),
                ("compressed_image", models.ImageField(upload_to="compressed_images/")),
            ],
        ),
        migrations.DeleteModel(
            name="ImageUpload",
        ),
    ]
