# Generated by Django 5.0.6 on 2024-07-04 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_image_delete_imageupload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="original_image",
        ),
    ]
